services:
  build-test-pipeline:
    build: .
    image: todo-app
    environment:
      - APP_URL=http://localhost:8080/todo
      - CI=true
    volumes:
      - ./tests/allure-result:/app/tests/allure-result
